import type { Metadata, Viewport } from "next";
import "./globals.css";
import MainNavigation from "@/components/layout/MainNavigation";
import Footer from "@/components/layout/Footer";
import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from "@/context/AuthContext";
import { CartProvider } from "@/context/CartContext";
import { NextUIProvider } from "@nextui-org/react";
import { ReactQueryClientProvider } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1.0,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryClientProvider>
          <AuthProvider>
            <CartProvider>
              <NextUIProvider>
                <MainNavigation />
                <main className="lg:pt-11 lg:px-36 pb-56 min-h-screen bg-[#f5f5f7] max-w-md lg:max-w-full">
                  {children}
                </main>
                <Toaster />
                <Footer />
              </NextUIProvider>
            </CartProvider>
          </AuthProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
