import type { Metadata, Viewport } from "next";
import "./globals.css";
import MainNavigation from "@/components/layout/MainNavigation";
import Footer from "@/components/layout/Footer";
import { Providers, ReactQueryClientProvider } from "./providers";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1.0,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body>
          <Providers>
            <MainNavigation />
            {/* <NavigationMenuDemo /> */}
            <main className="lg:mt-11 pb-56 min-h-screen bg-[#f5f5f7] max-w-md lg:max-w-full">
              {children}
            </main>
            <Toaster />
            <Footer />
          </Providers>
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
